animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']
puts "The first animal is: "  + animals[0]
puts "The fourth animal is: " + animals[3]
puts "The second animal is: " + animals[1]
puts "The fifth animal is: "  + animals[4]
puts "The third animal is: "  + animals[2]
puts "The sixth animal is: "  + animals[5]